ExpenseApp_Django/ExpenseApp/ExpenseApp/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("expensetracker.urls")),
    path('admin/', admin.site.urls),
    
]

ExpenseApp_Django/ExpenseApp/expensetracker/urls.py
from django.urls import path
from . import views

app_name = "expensetracker"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_sheet/<str:sheet_type>", views.add_sheet, name="add_sheet"),
    path("list_sheets/<str:sheet_type>", views.list_sheets, name="list_sheets"),
    path("view_recrods/<int:sheet_id>", views.view_records, name="view_records"),
    path("add_expense/<int:sheet_id>", views.add_expense, name="add_expense"),
    path("add_cc_payemnt/<int:sheet_id>", views.add_cc_payment, name="add_cc_payment"),
    path("add_income/<int:sheet_id>", views.add_income, name="add_income"),
    path("add_withdrawl/<int:sheet_id>", views.add_withdrawl, name="add_withdrawl"),
]

ExpenseApp_Django/ExpenseApp/expensetracker/models.py
from django.db import models
import datetime
import calendar

# Create your models here.
class Sheet(models.Model):
    '''
    This model is used to associate other models to a given transaction type, year, and month
    '''
    current_year = int(datetime.date.today().year)
    years = {year:year for year in range(2022, current_year+1)}
    months = {calendar.month_name[i]:calendar.month_name[i] for i in range(1, 13)}
    types = {"expense":"Expense", "ccPayment":"Credit Card Payment",
             "withdrawl":"Withdrawl", "income":"Income"}

    type = models.CharField(max_length=50, choices=types)
    year = models.SmallIntegerField(choices=years)
    month = models.CharField(max_length=20,choices=months)
    typeMonthYear = models.CharField(max_length=50, blank=True, null=True, unique=True)

    def save(self, *args, **kwargs):
        self.typeMonthYear = self.type + str(self.month)+str(self.year)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.typeMonthYear

class Expense(models.Model):
    '''
    This model is used to store expense transactions
    '''
    payTypes = {"cash":"Cash", "cc":"Credit Card", "bank":"Bank"}

    ccList = {"visa":"Visa",
              "americanExpress":"American Express"}


    categories = {"groceries":"Groceries/Home Goods", "internet":"Internet Bill",
                "gasBill":"Gas Bill", "electricBill":"Electric Bill", "waterBill":"Water Bill",
                "disney":"Disney/Hulu", "gasoline":"Gasoline/Maintenance", "hobbies":"Hobbies",
                "outsideFood":"Outside Food", "homeRepairs":"Home Repairs", "mortgage":"Mortgage","other":"Other"}


    date = models.DateField()
    amount = models.DecimalField(max_digits=100,decimal_places=2)
    description = models.CharField(max_length=50)
    payType = models.CharField(max_length=50, choices=payTypes)
    creditCard = models.CharField(max_length=50,choices=ccList)
    category = models.CharField(max_length=50,choices=categories)
    typeMonthYear = models.ForeignKey(Sheet, on_delete=models.CASCADE, null=True)
    

class Income(models.Model):
    '''
    This model is used to store income transactions
    '''

    date = models.DateField()
    amount = models.DecimalField(max_digits=100,decimal_places=2)
    cashOrBank = models.CharField(max_length=50,choices={"cash":"Cash","bank":"Bank"})
    description = models.CharField(max_length=50)
    typeMonthYear = models.ForeignKey(Sheet, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'income'

class CreditCardPayment(models.Model):
    '''
    This model is used to store credit card payment transactions
    '''
    ccList = {"visa":"Visa",
              "americanExpress":"American Express"}
    
    payTypes = {"cash":"Cash", "bank":"Bank"}

    date = models.DateField()
    creditCard = models.CharField(max_length=50,choices=ccList)
    amount = models.DecimalField(max_digits=100,decimal_places=2)
    payType = models.CharField(max_length=50, choices=payTypes)
    typeMonthYear = models.ForeignKey(Sheet, on_delete=models.CASCADE, null=True)

class Withdrawl(models.Model):
    '''
    This model is used to store withdrawl transactions
    '''
    date = models.DateField()
    amount = models.DecimalField(max_digits=100,decimal_places=2)
    typeMonthYear = models.ForeignKey(Sheet, on_delete=models.CASCADE, null=True)

ExpenseApp_Django/ExpenseApp/expensetracker/forms.py
from django import forms
from .models import Expense, Income, CreditCardPayment, Withdrawl, Sheet

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ["date","amount","description",
                  "payType","creditCard","category"]
        widgets = {
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ["date","amount","cashOrBank","description"]
        widgets = {
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

class CreditCardPaymentForm(forms.ModelForm):
    class Meta:
        model = CreditCardPayment
        fields = ["date", "creditCard", "amount", "payType"]
        widgets = {
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

class WithdrawlForm(forms.ModelForm):
    class Meta:
        model = Withdrawl
        fields = ["date", "amount"]
        widgets = {
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

class SheetForm(forms.ModelForm):
    class Meta:
        model = Sheet
        fields = ["type", "year", "month"]
        widgets = {
            "type":forms.widgets.TextInput(attrs={"readonly":"readonly"})
        }

ExpenseApp_Django/ExpenseApp/expensetracker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ExpenseForm, IncomeForm, SheetForm, CreditCardPaymentForm, WithdrawlForm
from .models import Sheet

# Create your views here.
def index(request):
    '''
    This function renders the home page of the application.


    Parameters
    -----------
    None

    Return
    ------
    None
    '''
    return render(request,"expensetracker/index.html")

def add_sheet(request, sheet_type):
    '''
    This function renders the form for adding a new Sheet object.


    Parameters
    -----------
    sheet_type: str
        the type for the data that the Sheet is being created for (e.g. 'expense')

    Return
    ------
    None
    '''
    if request.method != "POST":
        form = SheetForm(initial={"type":sheet_type})
    else:
        form = SheetForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("expensetracker:list_sheets", sheet_type=sheet_type)
    
    context = {"form":form, "sheet_type":sheet_type}
    return render(request, "expensetracker/add_sheet.html", context=context)


def list_sheets(request, sheet_type):
    '''
    This function renders the list of "sheets" available for the given sheet type.


    Parameters
    -----------
    sheet_type: str
        the type for the data that the Sheet is being created for (e.g. 'expense')

    Return
    ------
    None
    '''
    sheets = Sheet.objects.filter(type=sheet_type)
    context = {"sheets":sheets, "sheet_type":sheet_type}
    return render(request, "expensetracker/list_sheets.html", context=context)

def view_records(request, sheet_id):
    '''
    This function renders a table of recrods for the given sheet.


    Parameters
    -----------
    sheet_id: int
        the id for the sheet that you are attempting to view

    Return
    ------
    None
    '''
    sheet = Sheet.objects.get(id=sheet_id)
    sheet_type = sheet.type

    if sheet_type == "expense":
        records = sheet.expense_set.order_by('date')
        template = "expensetracker/view_expenses.html"
    elif sheet_type == "income":
        records = sheet.income_set.order_by('date')
        template = "expensetracker/view_income.html"
    elif sheet_type == "ccPayment":
        records = sheet.creditcardpayment_set.order_by('date')
        template = "expensetracker/view_ccPyaments.html"
    elif sheet_type == "withdrawl":
        records = sheet.withdrawl_set.order_by('date')
        template = "expensetracker/view_withdrawls.html"
    

    context = {"records":records, "sheet":sheet}
    return render(request, template, context=context)


def add_expense(request, sheet_id):
    '''
    This function renders the form for you to add a new expense record.


    Parameters
    -----------
    sheet_id: int
        the id for the sheet that you what to associate the record to.

    Return
    ------
    None
    '''
    sheet = Sheet.objects.get(id=sheet_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = ExpenseForm()
    else:
        form = ExpenseForm(data=request.POST)
        if form.is_valid():
            new_expense = form.save(commit=False)
            new_expense.typeMonthYear = sheet
            new_expense.save()
            return redirect("expensetracker:view_expenses", sheet_id=sheet_id)

    context = {"form":form, "sheet":sheet}
    return render(request, "expensetracker/add_expense.html", context=context)
    

def add_income(request, sheet_id):
    '''
    This function renders the form for you to add a new income record.


    Parameters
    -----------
    sheet_id: int
        the id for the sheet that you what to associate the record to.

    Return
    ------
    None
    '''
    sheet = Sheet.objects.get(id=sheet_id)
    if request.method != 'POST':
        form = IncomeForm()
    else:
        form = IncomeForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.typeMonthYear = sheet
            new_entry.save()
            return redirect("expensetracker:view_income", sheet_id=sheet_id)
    
    context = {"sheet":sheet, "form":form}
    return render(request, "expensetracker/add_income.html", context=context)

def add_cc_payment(request, sheet_id):
    '''
    This function renders the form for you to add a new credit card payment record.


    Parameters
    -----------
    sheet_id: int
        the id for the sheet that you what to associate the record to.

    Return
    ------
    None
    '''
    sheet = Sheet.objects.get(id=sheet_id)
    if request.method != "POST":
        form = CreditCardPaymentForm()
    else:
        form = CreditCardPaymentForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.typeMonthYear = sheet
            new_entry.save()
            return redirect("expensetracker:view_records", sheet_id = sheet_id)
    
    context = {"form":form, "sheet":sheet}
    return render(request, "expensetracker/add_cc_payment.html", context=context)

def add_withdrawl(request, sheet_id):
    '''
    This function renders the form for you to add a new withdrawl record.


    Parameters
    -----------
    sheet_id: int
        the id for the sheet that you what to associate the record to.

    Return
    ------
    None
    '''
    sheet = Sheet.objects.get(id=sheet_id)
    if request.method != "POST":
        form = WithdrawlForm()
    else:
        form = WithdrawlForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.typeMonthYear = sheet
            new_entry.save()
            return redirect("expensetracker:view_records", sheet_id = sheet_id)
    
    context = {"form":form, "sheet":sheet}
    return render(request, "expensetracker/add_withdrawl.html", context=context)

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/add_cc_payment.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<p>Add CC Payment:</p>
    <form action="{% url 'expensetracker:add_cc_payment' sheet.id %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/add_expense.html
{% extends 'expensetracker/base.html' %}

{% block content %}
    <p>Add Expense:</p>

    <form action="{% url 'expensetracker:add_expense' sheet.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Submit</button>
    </form>

{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/add_income.html
{% extends 'expensetracker/base.html' %}

{% block content %}
    <h2> Add Income:</h2>
    <form action="{% url 'expensetracker:add_income' sheet.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Submit</button>
    </form>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/add_sheet.html
{% extends 'expensetracker/base.html' %}

{% block content %}
    <form action="{% url 'expensetracker:add_sheet' sheet_type %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save</button>
    </form>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/add_withdrawl.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<p>Add Withdrawl:</p>
    <form action="{% url 'expensetracker:add_withdrawl' sheet.id %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/base.html
<a href="{% url 'expensetracker:index' %}">Home</a>
<h1>Expense Tracker</h1>

{% block content %}{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/index.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<p><a href="{% url 'expensetracker:list_sheets' 'expense'%}"><button type="button" >Expenses</button></a></p>
<p><a href="{% url 'expensetracker:list_sheets' 'income'%}"><button type="button" >Income</button></a></p>
<p><a href="{% url 'expensetracker:list_sheets' 'ccPayment'%}"><button type="button" >Credit Card Payments</button></a></p>
<p><a href="{% url 'expensetracker:list_sheets' 'withdrawl'%}"><button type="button" >Withdrawls</button></a></p>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/list_sheets.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<h2>{{ sheet_type }}</h2>
<ul>
    {% for sheet in sheets %}
        <li>
            <a href="{% url 'expensetracker:view_records' sheet.id %}">{{ sheet.month }}{{ sheet.year }}</a>       
        </li>
    {% empty %}
    {% endfor %}
</ul>
<a href="{% url 'expensetracker:add_sheet' sheet_type %}">New Sheet</a>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/view_ccPyaments.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<h2>CC Payments {{ sheet.month }} {{ sheet.year }}</h2>
<table>
<tr>
    <th>Date</th>
    <th>Credit Card</th>
    <th>Amount</th>
    <th>PayType</th>
</tr>   
    {% for record in records %}
        <tr>
            <td>{{ record.date }}</td>
            <td>{{ record.get_creditCard_display }}</td>
            <td>{{ record.amount }}</td>
            <td>{{ record.get_payType_display }}</td>
        </tr>   
    {% empty %}
    {% endfor %}
</table>
    <p><a href="{% url 'expensetracker:add_cc_payment' sheet.id %}">Add Record</a></p>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/view_expenses.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<h2>Expenses {{ sheet.month }} {{ sheet.year }}</h2>
<table>
<tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Description</th>
    <th>PayType</th>
    <th>Credit Card</th>
    <th>Category</th>
</tr>   
    {% for record in records %}
        <tr>
            <td>{{ record.date }}</td>
            <td>{{ record.amount }}</td>
            <td>{{ record.description }}</td>
            <td>{{ record.get_payType_display }}</td>
            <td>{{ record.get_creditCard_display }}</td>
            <td>{{ record.get_category_display }}</td>
        </tr>   
    {% empty %}
    {% endfor %}
</table>
    <p><a href="{% url 'expensetracker:add_expense' sheet.id %}">Add Record</a></p>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/view_income.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<h2>Income {{ sheet.month }} {{ sheet.year }}</h2>
<table>
<tr>
    <th>Date</th>
    <th>Amount</th>
    <th>CashOrBank</th>
    <th>Description</th>
</tr>   
    {% for record in records %}
        <tr>
            <td>{{ record.date }}</td>
            <td>{{ record.amount }}</td>
            <td>{{ record.get_cashOrBank_display }}</td>
            <td>{{ record.description }}</td>
        </tr>   
    {% empty %}
    {% endfor %}
</table>
    <p><a href="{% url 'expensetracker:add_income' sheet.id %}">Add Record</a></p>
{% endblock content %}

ExpenseApp_Django/ExpenseApp/expensetracker/templates/expensetracker/view_withdrawls.html
{% extends 'expensetracker/base.html' %}

{% block content %}
<h2>Withdrawl {{ sheet.month }} {{ sheet.year }}</h2>
<table>
<tr>
    <th>Date</th>
    <th>Amount</th>
</tr>   
    {% for record in records %}
        <tr>
            <td>{{ record.date }}</td>
            <td>{{ record.amount }}</td>
        </tr>   
    {% empty %}
    {% endfor %}
</table>
    <p><a href="{% url 'expensetracker:add_withdrawl' sheet.id %}">Add Record</a></p>
{% endblock content %}